# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01de7c499b9dca9aa4f81b8a1b5bc9006ac75d729db22242cc89826169d9170f88174a1419147af691472637b4afe22ee03f7dee98bf55c24d856f73c94271c0

test:
  secret_key_base: 52f5fc41f6288d9cb3d89ba952e82edca1ca202ba46219e6aa5b349d4f8f9c60826d7acefb6f82e71dc9204bc9ebe36cb83e32d5b7626adc20362835c1bb2829

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
